# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install                  # will run `yarn install` command
        
    - name: Environment variables
      run: |
        echo "${{secrets.TOKENV2}}" >> .env
        echo "${{secrets.TOKENV2_SECRET}}" >> .env
        echo "${{secrets.CONSUMER_KEY_V2}}" >> .env
        echo "${{secrets.CONSUMER_KEY_V2_SECRET}}" >> .env
        echo "${{secrets.BEARER_TOKEN}}" >> .env
        echo "${{secrets.AWS_ACCESS_KEY_ID}}" >> .env
        echo "${{secrets.AWS_SECRET_ACCESS_KEY}}" >> .env
        echo "${{secrets.AWS_SDK_LOAD_CONFIG}}" >> .env
        echo "${{secrets.NGROK_SECRET}}" >> .env
        echo "${{secrets.SHEETDB_ADMIN_MENU}}" >> .env
        echo "${{secrets.BOT_ID}}" >> .env
        echo "${{secrets.STORAGE_SAVE}}" >> .env
        echo "${{secrets.SERVER_RESTART}}" >> .env
        echo "${{secrets.POST_STREAM_IMG_PERCENT}}" >> .env
        echo "${{secrets.MIN_FOLLOWERS_WEBHOOK}}" >> .env
        echo "${{secrets.MAX_DAILY_USAGE}}" >> .env
        echo "${{secrets.ANTI_SPAM_SECONDS}}" >> .env
        echo "${{secrets.HEAD_ADMIN_ID}}" >> .env
        echo "${{secrets.PORT}}" >> .env
        
    - run: sudo pm2 restart BOT --cron-restart="0 */8 * * *"
